/* =========================================================
   GENERATED by tools/build-wger.mjs — do not edit by hand.

   Exercise names, photos and muscle data come from the wger.de open
   fitness database (https://wger.de), used under the licences recorded
   in ATTRIBUTION.md. Images live in img/ex/ so the app works offline.

   PHOTOS attaches a real photo to a hand-picked IronLog machine.
   EXTRA adds 150 further exercises that ship with their own picture.
   ========================================================= */
(function (global) {
  'use strict';
  var DIR = 'img/ex/';

  /* IronLog machine id -> photo file (hand-verified pairs only) */
  var PHOTOS = {
    "hip-adduction": "12.png",
    "bench-press": "73.png",
    "barbell-row": "83.jpg",
    "barbell-curl": "91.png",
    "db-curl": "92.png",
    "cable-curl": "95.png",
    "chest-press-machine": "129.jpg",
    "calf-leg-press": "146.jpg",
    "lat-pulldown": "158.jpg",
    "deadlift": "184.jpg",
    "dips-chest": "194.png",
    "dips-triceps": "197.png",
    "goblet-squat": "203.jpg",
    "walking-lunge": "206.jpg",
    "db-fly": "238.jpg",
    "skullcrusher": "246.png",
    "front-raise": "256.jpg",
    "hammer-curl": "272.png",
    "cable-crossover": "323.jpg",
    "lateral-raise-db": "348.jpg",
    "leg-curl-lying": "365.jpg",
    "leg-curl-seated": "366.jpg",
    "leg-extension": "369.jpg",
    "leg-press": "371.png",
    "hack-squat": "375.png",
    "plank": "458.png",
    "preacher-curl": "465.png",
    "pull-up": "475.jpg",
    "t-bar-row": "513.png",
    "incline-db-press": "537.png",
    "incline-press-machine": "539.png",
    "shoulder-press-machine": "543.png",
    "db-shoulder-press": "567.jpg",
    "shrug-barbell": "571.png",
    "shrug-db": "572.jpg",
    "calf-standing": "622.jpg",
    "overhead-triceps-cable": "659.jpg",
    "upright-row": "691.jpg",
    "smith-bench": "925.png",
    "pec-deck": "926.png",
    "captains-chair": "978.png",
    "hanging-leg-raise": "979.png",
    "seated-cable-row": "1117.jpg",
    "lat-pulldown-close": "1127.jpg",
    "cable-kickback": "1131.jpg",
    "triceps-pushdown": "1185.jpg",
    "chest-supported-row": "1283.jpg",
    "back-extension": "1348.png",
    "lateral-raise-cable": "1378.jpg",
    "push-up": "1551.jpg",
    "treadmill": "1615.jpg",
    "bike": "1618.png",
    "calf-seated": "1620.jpg",
    "romanian-deadlift": "1652.jpg",
    "bulgarian-split": "1706.jpg",
    "straight-arm-pulldown": "1726.jpg",
    "smith-squat": "1747.jpg",
    "hip-abduction": "1748.jpg",
    "squat": "1801.jpg",
    "overhead-press": "1893.png"
  };

  var EXTRA = [
   {
    "id": "w-axe-hold",
    "name": "Axe Hold",
    "group": "arms",
    "art": "dumbbellPair",
    "equip": "dumbbell",
    "metric": "time",
    "step": 2,
    "photo": "31.png",
    "muscles": [],
    "wger": 31
   },
   {
    "id": "w-barbell-ab-rollout",
    "name": "Barbell Ab Rollout",
    "group": "core",
    "art": "plank",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "41.png",
    "muscles": [
     "Obliquus externus abdominis"
    ],
    "wger": 41
   },
   {
    "id": "w-barbell-wrist-curl",
    "name": "Barbell Wrist Curl",
    "group": "arms",
    "art": "preacherCurl",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "51.png",
    "muscles": [],
    "wger": 51
   },
   {
    "id": "w-benchpress-dumbbells",
    "name": "Benchpress Dumbbells",
    "group": "chest",
    "art": "pressMachine",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "75.jpg",
    "muscles": [
     "Chest"
    ],
    "wger": 75
   },
   {
    "id": "w-bench-press-narrow-grip",
    "name": "Bench Press Narrow Grip",
    "group": "arms",
    "art": "benchFlat",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "76.png",
    "muscles": [
     "Triceps"
    ],
    "wger": 76
   },
   {
    "id": "w-bent-high-pulls",
    "name": "Bent High Pulls",
    "group": "shoulders",
    "art": "dumbbellPair",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "79.png",
    "muscles": [
     "Trapezius"
    ],
    "wger": 79
   },
   {
    "id": "w-bent-over-dumbbell-rows",
    "name": "Bent Over Dumbbell Rows",
    "group": "back",
    "art": "seatedRow",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "81.jpg",
    "muscles": [
     "Lats"
    ],
    "wger": 81
   },
   {
    "id": "w-bent-over-rowing-reverse",
    "name": "Bent Over Rowing Reverse",
    "group": "back",
    "art": "barbellFloor",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "84.jpg",
    "muscles": [
     "Lats"
    ],
    "wger": 84
   },
   {
    "id": "w-biceps-curls-with-sz-bar",
    "name": "Biceps Curls With SZ-bar",
    "group": "arms",
    "art": "barbellFloor",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "94.jpg",
    "muscles": [
     "Biceps"
    ],
    "wger": 94
   },
   {
    "id": "w-butterfly",
    "name": "Butterfly",
    "group": "chest",
    "art": "pecDeck",
    "equip": "machine",
    "metric": "weight",
    "step": 2.5,
    "photo": "135.jpg",
    "muscles": [
     "Chest"
    ],
    "wger": 135
   },
   {
    "id": "w-chin-up",
    "name": "Chin Up",
    "group": "back",
    "art": "pullupBar",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "152.png",
    "muscles": [
     "Biceps",
     "Lats"
    ],
    "wger": 152
   },
   {
    "id": "w-cross-bench-dumbbell-pullovers",
    "name": "Cross-Bench Dumbbell Pullovers",
    "group": "chest",
    "art": "latPulldown",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "161.png",
    "muscles": [
     "Lats",
     "Chest",
     "Serratus anterior"
    ],
    "wger": 161
   },
   {
    "id": "w-crunches",
    "name": "Crunches",
    "group": "core",
    "art": "abCrunchMachine",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "167.png",
    "muscles": [
     "Abs"
    ],
    "wger": 167
   },
   {
    "id": "w-incline-crunches",
    "name": "Incline Crunches",
    "group": "core",
    "art": "abCrunchMachine",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "171.png",
    "muscles": [
     "Abs"
    ],
    "wger": 171
   },
   {
    "id": "w-decline-bench-press-barbell",
    "name": "Decline Bench Press Barbell",
    "group": "chest",
    "art": "benchFlat",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "185.jpg",
    "muscles": [
     "Chest"
    ],
    "wger": 185
   },
   {
    "id": "w-fly-with-cable",
    "name": "Fly With Cable",
    "group": "chest",
    "art": "cableCrossover",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "237.jpg",
    "muscles": [
     "Chest"
    ],
    "wger": 237
   },
   {
    "id": "w-front-squats",
    "name": "Front Squats",
    "group": "legs",
    "art": "powerRack",
    "equip": "barbell",
    "metric": "weight",
    "step": 5,
    "photo": "257.png",
    "muscles": [
     "Glutes"
    ],
    "wger": 257
   },
   {
    "id": "w-hammercurls-on-cable",
    "name": "Hammercurls on Cable",
    "group": "arms",
    "art": "cableTower",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "275.png",
    "muscles": [
     "Biceps"
    ],
    "wger": 275
   },
   {
    "id": "w-handstand-pushup",
    "name": "Handstand Pushup",
    "group": "shoulders",
    "art": "plank",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "282.png",
    "muscles": [
     "Shoulders",
     "Triceps"
    ],
    "wger": 282
   },
   {
    "id": "w-high-knee-jumps",
    "name": "High Knee Jumps",
    "group": "cardio",
    "art": "treadmill",
    "equip": "machine",
    "metric": "cardio",
    "step": 2.5,
    "photo": "285.png",
    "muscles": [
     "Hamstrings",
     "Calves",
     "Quads"
    ],
    "wger": 285
   },
   {
    "id": "w-hollow-hold",
    "name": "Hollow Hold",
    "group": "core",
    "art": "plank",
    "equip": "bodyweight",
    "metric": "time",
    "step": 2.5,
    "photo": "297.png",
    "muscles": [
     "Obliquus externus abdominis",
     "Abs"
    ],
    "wger": 297
   },
   {
    "id": "w-jumping-jacks",
    "name": "Jumping Jacks",
    "group": "legs",
    "art": "generic",
    "equip": "machine",
    "metric": "weight",
    "step": 2.5,
    "photo": "320.png",
    "muscles": [
     "Quads"
    ],
    "wger": 320
   },
   {
    "id": "w-lateral-rows-on-cable-one-armed",
    "name": "Lateral Rows on Cable, One Armed",
    "group": "shoulders",
    "art": "seatedRow",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "349.png",
    "muscles": [
     "Shoulders"
    ],
    "wger": 349
   },
   {
    "id": "w-leg-curl",
    "name": "Leg Curl",
    "group": "legs",
    "art": "legCurlSeated",
    "equip": "machine",
    "metric": "weight",
    "step": 2.5,
    "photo": "364.png",
    "muscles": [
     "Hamstrings",
     "Glutes"
    ],
    "wger": 364
   },
   {
    "id": "w-leg-curls-standing",
    "name": "Leg Curls (standing)",
    "group": "legs",
    "art": "legCurlSeated",
    "equip": "machine",
    "metric": "weight",
    "step": 2.5,
    "photo": "367.jpg",
    "muscles": [
     "Hamstrings"
    ],
    "wger": 367
   },
   {
    "id": "w-leg-presses-narrow",
    "name": "Leg Presses (narrow)",
    "group": "legs",
    "art": "legPress",
    "equip": "machine",
    "metric": "weight",
    "step": 5,
    "photo": "373.jpg",
    "muscles": [
     "Quads"
    ],
    "wger": 373
   },
   {
    "id": "w-leg-raises-lying",
    "name": "Leg Raises, Lying",
    "group": "core",
    "art": "plank",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "377.png",
    "muscles": [
     "Abs"
    ],
    "wger": 377
   },
   {
    "id": "w-long-pulley-low-row",
    "name": "Long-Pulley (low Row)",
    "group": "back",
    "art": "seatedRow",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "394.jpg",
    "muscles": [
     "Lats"
    ],
    "wger": 394
   },
   {
    "id": "w-military-press-mit-sz-bar",
    "name": "Military Press mit SZ-Bar",
    "group": "shoulders",
    "art": "shoulderPressMachine",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "418.jpg",
    "muscles": [
     "Shoulders"
    ],
    "wger": 418
   },
   {
    "id": "w-negative-crunches",
    "name": "Negative Crunches",
    "group": "core",
    "art": "abCrunchMachine",
    "equip": "machine",
    "metric": "weight",
    "step": 2.5,
    "photo": "427.png",
    "muscles": [
     "Abs"
    ],
    "wger": 427
   },
   {
    "id": "w-pike-push-ups",
    "name": "Pike Push Ups",
    "group": "arms",
    "art": "plank",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "454.png",
    "muscles": [
     "Chest"
    ],
    "wger": 454
   },
   {
    "id": "w-pistol-squat",
    "name": "Pistol Squat",
    "group": "legs",
    "art": "plank",
    "equip": "machine",
    "metric": "weight",
    "step": 5,
    "photo": "456.jpg",
    "muscles": [
     "Hamstrings",
     "Glutes"
    ],
    "wger": 456
   },
   {
    "id": "w-push-press",
    "name": "Push Press",
    "group": "shoulders",
    "art": "shoulderPressMachine",
    "equip": "machine",
    "metric": "weight",
    "step": 2.5,
    "photo": "478.jpg",
    "muscles": [
     "Trapezius"
    ],
    "wger": 478
   },
   {
    "id": "w-rack-deadlift",
    "name": "Rack Deadlift",
    "group": "back",
    "art": "barbellFloor",
    "equip": "machine",
    "metric": "weight",
    "step": 5,
    "photo": "484.jpg",
    "muscles": [
     "Glutes"
    ],
    "wger": 484
   },
   {
    "id": "w-rear-delt-raises",
    "name": "Rear Delt Raises",
    "group": "shoulders",
    "art": "reversePecDeck",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "487.jpg",
    "muscles": [],
    "wger": 487
   },
   {
    "id": "w-rowing-seated-narrow-grip",
    "name": "Rowing seated, narrow grip",
    "group": "back",
    "art": "seatedRow",
    "equip": "machine",
    "metric": "weight",
    "step": 2.5,
    "photo": "512.jpg",
    "muscles": [
     "Lats"
    ],
    "wger": 512
   },
   {
    "id": "w-incline-bench-press-barbell",
    "name": "Incline Bench Press - Barbell",
    "group": "chest",
    "art": "benchIncline",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "538.jpg",
    "muscles": [
     "Chest"
    ],
    "wger": 538
   },
   {
    "id": "w-shoulder-press-barbell",
    "name": "Shoulder Press, Barbell",
    "group": "shoulders",
    "art": "shoulderPressMachine",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "566.jpg",
    "muscles": [
     "Shoulders"
    ],
    "wger": 566
   },
   {
    "id": "w-shoulder-shrug",
    "name": "Shoulder Shrug",
    "group": "shoulders",
    "art": "barbellFloor",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "570.png",
    "muscles": [
     "Trapezius"
    ],
    "wger": 570
   },
   {
    "id": "w-side-crunch",
    "name": "Side Crunch",
    "group": "core",
    "art": "abCrunchMachine",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "576.png",
    "muscles": [
     "Obliquus externus abdominis"
    ],
    "wger": 576
   },
   {
    "id": "w-sumo-deadlift",
    "name": "Sumo Deadlift",
    "group": "legs",
    "art": "barbellFloor",
    "equip": "machine",
    "metric": "weight",
    "step": 5,
    "photo": "630.png",
    "muscles": [
     "Hamstrings",
     "Glutes",
     "Quads"
    ],
    "wger": 630
   },
   {
    "id": "w-upright-row-sz-bar",
    "name": "Upright Row, SZ-bar",
    "group": "shoulders",
    "art": "barbellFloor",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "693.jpg",
    "muscles": [
     "Shoulders",
     "Trapezius"
    ],
    "wger": 693
   },
   {
    "id": "w-upright-row-w-dumbbells",
    "name": "Upright Row w/ Dumbbells",
    "group": "shoulders",
    "art": "barbellFloor",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "694.jpg",
    "muscles": [
     "Shoulders",
     "Trapezius"
    ],
    "wger": 694
   },
   {
    "id": "w-tricep-pushdown-on-cable",
    "name": "Tricep Pushdown on Cable",
    "group": "arms",
    "art": "pushdown",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "805.png",
    "muscles": [
     "Triceps"
    ],
    "wger": 805
   },
   {
    "id": "w-cable-rear-delt-fly",
    "name": "Cable Rear Delt Fly",
    "group": "shoulders",
    "art": "cableCrossover",
    "equip": "cable",
    "metric": "weight",
    "step": 1.25,
    "photo": "822.jpg",
    "muscles": [
     "Shoulders",
     "Trapezius"
    ],
    "wger": 822
   },
   {
    "id": "w-incline-bench-reverse-fly",
    "name": "Incline Bench Reverse Fly",
    "group": "back",
    "art": "benchIncline",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "828.jpg",
    "muscles": [
     "Shoulders",
     "Trapezius"
    ],
    "wger": 828
   },
   {
    "id": "w-reverse-nordic-curl",
    "name": "Reverse Nordic Curl",
    "group": "legs",
    "art": "barbellFloor",
    "equip": "machine",
    "metric": "weight",
    "step": 2.5,
    "photo": "909.png",
    "muscles": [
     "Quads"
    ],
    "wger": 909
   },
   {
    "id": "w-straight-bar-cable-curls",
    "name": "Straight Bar Cable Curls",
    "group": "arms",
    "art": "cableTower",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "912.png",
    "muscles": [
     "Biceps"
    ],
    "wger": 912
   },
   {
    "id": "w-smith-press",
    "name": "Smith Press",
    "group": "shoulders",
    "art": "smithMachine",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "916.png",
    "muscles": [
     "Shoulders"
    ],
    "wger": 916
   },
   {
    "id": "w-quadriped-arm-and-leg-raise",
    "name": "Quadriped Arm and Leg Raise",
    "group": "back",
    "art": "plank",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "957.png",
    "muscles": [
     "Shoulders",
     "Glutes",
     "Serratus anterior"
    ],
    "wger": 957
   },
   {
    "id": "w-biceps-with-trx",
    "name": "Biceps with TRX",
    "group": "arms",
    "art": "plank",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "958.jpg",
    "muscles": [
     "Biceps"
    ],
    "wger": 958
   },
   {
    "id": "w-trx-rows",
    "name": "TRX Rows",
    "group": "back",
    "art": "seatedRow",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "959.png",
    "muscles": [
     "Shoulders",
     "Biceps",
     "Lats"
    ],
    "wger": 959
   },
   {
    "id": "w-kettlebell-swing",
    "name": "Kettlebell Swing",
    "group": "legs",
    "art": "kettlebell",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "960.png",
    "muscles": [
     "Shoulders",
     "Glutes"
    ],
    "wger": 960
   },
   {
    "id": "w-one-handed-kettlebell-curls",
    "name": "one-handed kettlebell curls",
    "group": "arms",
    "art": "dumbbellSingle",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "975.png",
    "muscles": [
     "Biceps"
    ],
    "wger": 975
   },
   {
    "id": "w-medicine-ball-booklet-crunch",
    "name": "Medicine ball booklet crunch",
    "group": "core",
    "art": "abCrunchMachine",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "976.png",
    "muscles": [
     "Abs"
    ],
    "wger": 976
   },
   {
    "id": "w-box-squat",
    "name": "Box squat",
    "group": "legs",
    "art": "plank",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 5,
    "photo": "977.png",
    "muscles": [
     "Glutes",
     "Quads",
     "Soleus"
    ],
    "wger": 977
   },
   {
    "id": "w-step-ups",
    "name": "Step-ups",
    "group": "legs",
    "art": "dumbbellPair",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "981.png",
    "muscles": [
     "Glutes",
     "Quads"
    ],
    "wger": 981
   },
   {
    "id": "w-high-knees",
    "name": "High knees",
    "group": "cardio",
    "art": "treadmill",
    "equip": "bodyweight",
    "metric": "cardio",
    "step": 2.5,
    "photo": "983.png",
    "muscles": [],
    "wger": 983
   },
   {
    "id": "w-lunges",
    "name": "Lunges",
    "group": "legs",
    "art": "dumbbellPair",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "984.jpg",
    "muscles": [
     "Glutes",
     "Quads"
    ],
    "wger": 984
   },
   {
    "id": "w-bulgarian-split-squats-left",
    "name": "Bulgarian split squats left",
    "group": "legs",
    "art": "powerRack",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 5,
    "photo": "988.jpg",
    "muscles": [
     "Glutes",
     "Quads"
    ],
    "wger": 988
   },
   {
    "id": "w-kneeling-kickbacks",
    "name": "Kneeling kickbacks",
    "group": "glutes",
    "art": "gluteKickback",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "990.png",
    "muscles": [
     "Glutes"
    ],
    "wger": 990
   },
   {
    "id": "w-reverse-lunges",
    "name": "Reverse lunges",
    "group": "legs",
    "art": "dumbbellPair",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "999.jpg",
    "muscles": [
     "Glutes",
     "Quads"
    ],
    "wger": 999
   },
   {
    "id": "w-floor-dips",
    "name": "Floor dips",
    "group": "arms",
    "art": "dipStation",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "1000.jpg",
    "muscles": [
     "Triceps"
    ],
    "wger": 1000
   },
   {
    "id": "w-kettlebell-deadlifts",
    "name": "Kettlebell deadlifts",
    "group": "back",
    "art": "barbellFloor",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 5,
    "photo": "1003.png",
    "muscles": [
     "Hamstrings",
     "Glutes"
    ],
    "wger": 1003
   },
   {
    "id": "w-alternating-bicep-curls",
    "name": "Alternating bicep curls",
    "group": "arms",
    "art": "barbellFloor",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1012.jpg",
    "muscles": [
     "Biceps"
    ],
    "wger": 1012
   },
   {
    "id": "w-single-arm-plank-to-row",
    "name": "Single Arm Plank to Row",
    "group": "back",
    "art": "plank",
    "equip": "dumbbell",
    "metric": "time",
    "step": 2,
    "photo": "1022.jpg",
    "muscles": [
     "Shoulders",
     "Biceps",
     "Brachialis"
    ],
    "wger": 1022
   },
   {
    "id": "w-hindu-pushups",
    "name": "Hindu Pushups",
    "group": "shoulders",
    "art": "generic",
    "equip": "machine",
    "metric": "weight",
    "step": 2.5,
    "photo": "1080.jpg",
    "muscles": [
     "Shoulders",
     "Chest"
    ],
    "wger": 1080
   },
   {
    "id": "w-dumbbell-floor-press",
    "name": "Dumbbell Floor Press",
    "group": "chest",
    "art": "benchFlat",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1084.jpg",
    "muscles": [
     "Chest"
    ],
    "wger": 1084
   },
   {
    "id": "w-close-grip-press-ups",
    "name": "Close-grip Press-ups",
    "group": "chest",
    "art": "pressMachine",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "1086.jpg",
    "muscles": [
     "Brachialis",
     "Lats",
     "Chest"
    ],
    "wger": 1086
   },
   {
    "id": "w-dumbbell-hang-power-cleans",
    "name": "Dumbbell Hang Power Cleans",
    "group": "back",
    "art": "pullupBar",
    "equip": "dumbbell",
    "metric": "time",
    "step": 2,
    "photo": "1087.jpg",
    "muscles": [
     "Hamstrings",
     "Glutes"
    ],
    "wger": 1087
   },
   {
    "id": "w-dumbbell-sumo-deadlift",
    "name": "Dumbbell sumo deadlift",
    "group": "legs",
    "art": "barbellFloor",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 5,
    "photo": "1088.jpg",
    "muscles": [
     "Hamstrings",
     "Glutes"
    ],
    "wger": 1088
   },
   {
    "id": "w-medicine-ball-twist",
    "name": "Medicine ball twist",
    "group": "core",
    "art": "torsoRotation",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "1089.jpg",
    "muscles": [
     "Obliquus externus abdominis",
     "Abs"
    ],
    "wger": 1089
   },
   {
    "id": "w-plank-shoulder-taps",
    "name": "Plank Shoulder Taps",
    "group": "core",
    "art": "plank",
    "equip": "bodyweight",
    "metric": "time",
    "step": 2.5,
    "photo": "1091.jpg",
    "muscles": [
     "Shoulders",
     "Glutes",
     "Abs"
    ],
    "wger": 1091
   },
   {
    "id": "w-seated-rear-delt-rise",
    "name": "Seated rear delt rise",
    "group": "back",
    "art": "reversePecDeck",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1098.jpg",
    "muscles": [
     "Lats"
    ],
    "wger": 1098
   },
   {
    "id": "w-wall-balls",
    "name": "Wall balls",
    "group": "legs",
    "art": "plank",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "1100.jpg",
    "muscles": [
     "Shoulders",
     "Glutes",
     "Quads"
    ],
    "wger": 1100
   },
   {
    "id": "w-seated-knee-tuck",
    "name": "Seated Knee Tuck",
    "group": "core",
    "art": "plank",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "1105.png",
    "muscles": [
     "Abs"
    ],
    "wger": 1105
   },
   {
    "id": "w-cable-concentration-curl",
    "name": "Cable Concentration Curl",
    "group": "arms",
    "art": "cableTower",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "1109.jpg",
    "muscles": [
     "Biceps",
     "Brachialis"
    ],
    "wger": 1109
   },
   {
    "id": "w-push-ups-decline",
    "name": "Push-Ups | Decline",
    "group": "chest",
    "art": "barbellFloor",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "1112.png",
    "muscles": [
     "Chest"
    ],
    "wger": 1112
   },
   {
    "id": "w-neutral-grip-chest-pulldown",
    "name": "Neutral-grip chest pulldown",
    "group": "back",
    "art": "latPulldown",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "1136.jpg",
    "muscles": [
     "Biceps",
     "Lats",
     "Serratus anterior"
    ],
    "wger": 1136
   },
   {
    "id": "w-high-pulley-pullover",
    "name": "High-pulley pullover",
    "group": "back",
    "art": "latPulldown",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "1137.jpg",
    "muscles": [
     "Lats",
     "Serratus anterior"
    ],
    "wger": 1137
   },
   {
    "id": "w-incline-bench-pulldown",
    "name": "Incline bench pulldown",
    "group": "back",
    "art": "latPulldown",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "1138.jpg",
    "muscles": [
     "Lats"
    ],
    "wger": 1138
   },
   {
    "id": "w-one-arm-bent-row",
    "name": "One Arm Bent Row",
    "group": "back",
    "art": "barbellFloor",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "1186.jpg",
    "muscles": [
     "Lats"
    ],
    "wger": 1186
   },
   {
    "id": "w-side-bend",
    "name": "Side bend",
    "group": "core",
    "art": "torsoRotation",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1188.jpg",
    "muscles": [
     "Obliquus externus abdominis"
    ],
    "wger": 1188
   },
   {
    "id": "w-alternating-biceps-curls-with-dumbbell",
    "name": "Alternating Biceps Curls With Dumbbell",
    "group": "arms",
    "art": "dumbbellSingle",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1192.jpg",
    "muscles": [
     "Biceps"
    ],
    "wger": 1192
   },
   {
    "id": "w-russian-twist",
    "name": "Russian Twist",
    "group": "core",
    "art": "torsoRotation",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1193.png",
    "muscles": [
     "Lats",
     "Obliquus externus abdominis",
     "Abs"
    ],
    "wger": 1193
   },
   {
    "id": "w-pallof-press",
    "name": "Pallof Press",
    "group": "core",
    "art": "cableTower",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "1194.png",
    "muscles": [
     "Shoulders",
     "Glutes",
     "Obliquus externus abdominis"
    ],
    "wger": 1194
   },
   {
    "id": "w-inverted-rows",
    "name": "Inverted Rows",
    "group": "chest",
    "art": "barbellFloor",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "1198.jpg",
    "muscles": [
     "Biceps",
     "Lats"
    ],
    "wger": 1198
   },
   {
    "id": "w-finger-pushup",
    "name": "Finger Pushup",
    "group": "arms",
    "art": "plank",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "1217.png",
    "muscles": [
     "Chest"
    ],
    "wger": 1217
   },
   {
    "id": "w-dumbbell-bicep-curl-to-press",
    "name": "Dumbbell bicep curl to press",
    "group": "arms",
    "art": "dumbbellSingle",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1226.jpg",
    "muscles": [
     "Biceps"
    ],
    "wger": 1226
   },
   {
    "id": "w-double-leg-calf-raise",
    "name": "Double Leg Calf Raise",
    "group": "legs",
    "art": "calfStanding",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 5,
    "photo": "1243.jpg",
    "muscles": [
     "Calves",
     "Soleus"
    ],
    "wger": 1243
   },
   {
    "id": "w-reverse-grip-barbell-curls",
    "name": "Reverse Grip Barbell Curls",
    "group": "arms",
    "art": "barbellFloor",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "1290.jpg",
    "muscles": [
     "Biceps"
    ],
    "wger": 1290
   },
   {
    "id": "w-low-cable-cross-over-nb",
    "name": "Low-Cable Cross-Over - NB",
    "group": "chest",
    "art": "cableCrossover",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "1296.jpg",
    "muscles": [
     "Chest"
    ],
    "wger": 1296
   },
   {
    "id": "w-high-cable-cross-tricep-extention-nb",
    "name": "High-Cable Cross Tricep Extention - NB",
    "group": "arms",
    "art": "cableTower",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "1298.jpg",
    "muscles": [
     "Triceps"
    ],
    "wger": 1298
   },
   {
    "id": "w-lateral-push-off",
    "name": "Lateral Push Off",
    "group": "legs",
    "art": "plank",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "1325.jpg",
    "muscles": [
     "Calves"
    ],
    "wger": 1325
   },
   {
    "id": "w-triceps-overhead-dumbbell",
    "name": "Triceps Overhead (Dumbbell)",
    "group": "arms",
    "art": "dumbbellPair",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1336.png",
    "muscles": [
     "Triceps"
    ],
    "wger": 1336
   },
   {
    "id": "w-shoulder-raise-dumbbell",
    "name": "Shoulder Raise (Dumbbell)",
    "group": "shoulders",
    "art": "dumbbellPair",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1338.png",
    "muscles": [
     "Shoulders"
    ],
    "wger": 1338
   },
   {
    "id": "w-dumbbell-hex-press",
    "name": "Dumbbell Hex Press",
    "group": "chest",
    "art": "benchFlat",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1353.png",
    "muscles": [
     "Chest",
     "Triceps"
    ],
    "wger": 1353
   },
   {
    "id": "w-torso-twist",
    "name": "Torso Twist",
    "group": "core",
    "art": "torsoRotation",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "1377.jpg",
    "muscles": [
     "Abs"
    ],
    "wger": 1377
   },
   {
    "id": "w-hamstring-kicks",
    "name": "Hamstring Kicks",
    "group": "legs",
    "art": "plank",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "1387.jpg",
    "muscles": [
     "Hamstrings"
    ],
    "wger": 1387
   },
   {
    "id": "w-good-morning",
    "name": "Good Morning",
    "group": "legs",
    "art": "barbellFloor",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "1392.png",
    "muscles": [
     "Hamstrings"
    ],
    "wger": 1392
   },
   {
    "id": "w-seated-w-curl",
    "name": "Seated W Curl",
    "group": "arms",
    "art": "barbellFloor",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1448.png",
    "muscles": [
     "Biceps",
     "Brachialis"
    ],
    "wger": 1448
   },
   {
    "id": "w-sit-up-elbow-thrust",
    "name": "Sit Up Elbow Thrust",
    "group": "core",
    "art": "plank",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "1479.png",
    "muscles": [
     "Obliquus externus abdominis",
     "Abs"
    ],
    "wger": 1479
   },
   {
    "id": "w-pendular-hack",
    "name": "Pendular hack",
    "group": "legs",
    "art": "hackSquat",
    "equip": "machine",
    "metric": "weight",
    "step": 5,
    "photo": "1521.jpg",
    "muscles": [],
    "wger": 1521
   },
   {
    "id": "w-clap-push-up",
    "name": "Clap Push-UP",
    "group": "chest",
    "art": "plank",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "1554.jpg",
    "muscles": [
     "Chest"
    ],
    "wger": 1554
   },
   {
    "id": "w-devil-s-press",
    "name": "Devil’s Press",
    "group": "shoulders",
    "art": "pressMachine",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1556.jpg",
    "muscles": [
     "Shoulders",
     "Glutes",
     "Chest"
    ],
    "wger": 1556
   },
   {
    "id": "w-alternating-dumbbell-hammer-curl",
    "name": "Alternating dumbbell hammer curl",
    "group": "arms",
    "art": "dumbbellSingle",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1567.png",
    "muscles": [
     "Biceps"
    ],
    "wger": 1567
   },
   {
    "id": "w-bird-dog",
    "name": "Bird Dog",
    "group": "core",
    "art": "plank",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "1572.jpg",
    "muscles": [
     "Abs"
    ],
    "wger": 1572
   },
   {
    "id": "w-ab-wheel",
    "name": "Ab wheel",
    "group": "core",
    "art": "plank",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "1573.png",
    "muscles": [
     "Abs"
    ],
    "wger": 1573
   },
   {
    "id": "w-trap-press",
    "name": "Trap press",
    "group": "shoulders",
    "art": "shoulderPressMachine",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "1581.jpg",
    "muscles": [
     "Trapezius"
    ],
    "wger": 1581
   },
   {
    "id": "w-side-laying-interior-rotation",
    "name": "Side-laying interior rotation",
    "group": "shoulders",
    "art": "barbellFloor",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "1582.jpg",
    "muscles": [
     "Trapezius"
    ],
    "wger": 1582
   },
   {
    "id": "w-sliding-lateral-lunge",
    "name": "Sliding Lateral Lunge",
    "group": "legs",
    "art": "dumbbellPair",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "1604.jpg",
    "muscles": [
     "Hamstrings",
     "Glutes",
     "Quads"
    ],
    "wger": 1604
   },
   {
    "id": "w-kettlebell-sumo-deadlift",
    "name": "kettlebell sumo deadlift",
    "group": "legs",
    "art": "barbellFloor",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 5,
    "photo": "1612.jpg",
    "muscles": [
     "Hamstrings",
     "Glutes",
     "Quads"
    ],
    "wger": 1612
   },
   {
    "id": "w-rubber-band-glute-kickback",
    "name": "rubber band glute kickback",
    "group": "glutes",
    "art": "gluteKickback",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "1613.jpg",
    "muscles": [
     "Glutes"
    ],
    "wger": 1613
   },
   {
    "id": "w-dumbbell-donkey-kick",
    "name": "Dumbbell donkey kick",
    "group": "glutes",
    "art": "gluteKickback",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1616.jpg",
    "muscles": [
     "Hamstrings",
     "Glutes"
    ],
    "wger": 1616
   },
   {
    "id": "w-unilateral-cable-row",
    "name": "Unilateral Cable row",
    "group": "back",
    "art": "seatedRow",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "1621.jpg",
    "muscles": [
     "Lats",
     "Serratus anterior"
    ],
    "wger": 1621
   },
   {
    "id": "w-rope-pullover-row",
    "name": "Rope Pullover/row",
    "group": "back",
    "art": "latPulldown",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "1634.png",
    "muscles": [
     "Lats"
    ],
    "wger": 1634
   },
   {
    "id": "w-modified-pulldown",
    "name": "Modified pulldown",
    "group": "back",
    "art": "latPulldown",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "1635.png",
    "muscles": [
     "Lats"
    ],
    "wger": 1635
   },
   {
    "id": "w-single-arm-row",
    "name": "Single arm row",
    "group": "back",
    "art": "seatedRow",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "1637.png",
    "muscles": [
     "Lats"
    ],
    "wger": 1637
   },
   {
    "id": "w-barbell-clean-and-press",
    "name": "Barbell Clean and press",
    "group": "shoulders",
    "art": "shoulderPressMachine",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1638.jpg",
    "muscles": [
     "Shoulders",
     "Chest"
    ],
    "wger": 1638
   },
   {
    "id": "w-dumbbell-bent-over-face-pull",
    "name": "Dumbbell Bent Over Face Pull",
    "group": "back",
    "art": "cableTower",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1639.jpg",
    "muscles": [
     "Shoulders",
     "Lats"
    ],
    "wger": 1639
   },
   {
    "id": "w-dumbbell-front-squat",
    "name": "Dumbbell Front Squat",
    "group": "legs",
    "art": "dumbbellPair",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 5,
    "photo": "1640.jpg",
    "muscles": [
     "Glutes",
     "Quads"
    ],
    "wger": 1640
   },
   {
    "id": "w-kettlebell-one-legged-deadlift",
    "name": "Kettlebell One Legged Deadlift",
    "group": "legs",
    "art": "barbellFloor",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 5,
    "photo": "1641.jpg",
    "muscles": [
     "Glutes"
    ],
    "wger": 1641
   },
   {
    "id": "w-dumbbell-hip-thrust",
    "name": "Dumbbell Hip Thrust",
    "group": "glutes",
    "art": "hipThrustMachine",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 5,
    "photo": "1642.jpg",
    "muscles": [
     "Glutes",
     "Quads"
    ],
    "wger": 1642
   },
   {
    "id": "w-weighted-crunch",
    "name": "Weighted Crunch",
    "group": "core",
    "art": "abCrunchMachine",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1648.jpg",
    "muscles": [
     "Obliquus externus abdominis"
    ],
    "wger": 1648
   },
   {
    "id": "w-dumbbell-side-bend",
    "name": "Dumbbell Side Bend",
    "group": "core",
    "art": "torsoRotation",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1650.jpg",
    "muscles": [
     "Obliquus externus abdominis"
    ],
    "wger": 1650
   },
   {
    "id": "w-dumbbell-rear-lunge",
    "name": "Dumbbell Rear Lunge",
    "group": "legs",
    "art": "dumbbellPair",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1651.jpg",
    "muscles": [
     "Glutes",
     "Quads"
    ],
    "wger": 1651
   },
   {
    "id": "w-dumbbell-side-squat",
    "name": "Dumbbell Side Squat",
    "group": "legs",
    "art": "dumbbellPair",
    "equip": "machine",
    "metric": "weight",
    "step": 5,
    "photo": "1653.jpg",
    "muscles": [
     "Glutes",
     "Quads"
    ],
    "wger": 1653
   },
   {
    "id": "w-machine-lateral-raise",
    "name": "Machine Lateral Raise",
    "group": "shoulders",
    "art": "pullupBar",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 1.25,
    "photo": "1654.jpg",
    "muscles": [
     "Shoulders"
    ],
    "wger": 1654
   },
   {
    "id": "w-seated-row-machine",
    "name": "Seated Row (Machine)",
    "group": "back",
    "art": "seatedRow",
    "equip": "machine",
    "metric": "weight",
    "step": 2.5,
    "photo": "1725.jpg",
    "muscles": [
     "Lats"
    ],
    "wger": 1725
   },
   {
    "id": "w-face-pulls-with-yellow-green-band",
    "name": "Face pulls with yellow/green band",
    "group": "back",
    "art": "cableTower",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 1.25,
    "photo": "1732.jpg",
    "muscles": [
     "Lats"
    ],
    "wger": 1732
   },
   {
    "id": "w-isometric-squat-to-failure",
    "name": "Isometric Squat to Failure",
    "group": "legs",
    "art": "plank",
    "equip": "bodyweight",
    "metric": "time",
    "step": 5,
    "photo": "1733.jpg",
    "muscles": [
     "Glutes",
     "Quads"
    ],
    "wger": 1733
   },
   {
    "id": "w-single-leg-lunge-with-kettlebell",
    "name": "Single-Leg Lunge with Kettlebell:",
    "group": "legs",
    "art": "dumbbellPair",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1734.jpg",
    "muscles": [
     "Calves",
     "Glutes",
     "Quads"
    ],
    "wger": 1734
   },
   {
    "id": "w-single-leg-side-glute-press",
    "name": "Single-leg side glute press",
    "group": "glutes",
    "art": "pressMachine",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "1735.jpg",
    "muscles": [
     "Calves",
     "Glutes",
     "Quads"
    ],
    "wger": 1735
   },
   {
    "id": "w-single-leg-deadlift-with-dumbbell",
    "name": "Single-Leg Deadlift with Dumbbell",
    "group": "legs",
    "art": "barbellFloor",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 5,
    "photo": "1736.jpg",
    "muscles": [
     "Hamstrings",
     "Glutes"
    ],
    "wger": 1736
   },
   {
    "id": "w-neutral-grip-pull-ups-or-trx-rows",
    "name": "Neutral-grip pull-ups or TRX rows",
    "group": "arms",
    "art": "pullupBar",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "1738.jpg",
    "muscles": [
     "Lats"
    ],
    "wger": 1738
   },
   {
    "id": "w-machine-side-lateral-raises",
    "name": "Machine Side Lateral Raises",
    "group": "shoulders",
    "art": "pullupBar",
    "equip": "machine",
    "metric": "weight",
    "step": 1.25,
    "photo": "1744.jpg",
    "muscles": [
     "Shoulders"
    ],
    "wger": 1744
   },
   {
    "id": "w-cable-front-raise-with-a-small-bar",
    "name": "Cable Front Raise with a small bar",
    "group": "shoulders",
    "art": "cableTower",
    "equip": "cable",
    "metric": "weight",
    "step": 1.25,
    "photo": "1745.jpg",
    "muscles": [
     "Shoulders"
    ],
    "wger": 1745
   },
   {
    "id": "w-barbell-step-back-lunge",
    "name": "Barbell Step Back Lunge",
    "group": "legs",
    "art": "dumbbellPair",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "1830.jpg",
    "muscles": [
     "Quads"
    ],
    "wger": 1830
   },
   {
    "id": "w-hammerstrength-decline-chest-press",
    "name": "Hammerstrength Decline Chest Press",
    "group": "chest",
    "art": "pressMachine",
    "equip": "machine",
    "metric": "weight",
    "step": 2.5,
    "photo": "1831.jpg",
    "muscles": [
     "Chest"
    ],
    "wger": 1831
   },
   {
    "id": "w-decline-bench-leg-raise",
    "name": "Decline Bench Leg Raise",
    "group": "core",
    "art": "plank",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "1889.png",
    "muscles": [
     "Abs"
    ],
    "wger": 1889
   },
   {
    "id": "w-tricep-rope-pushdowns",
    "name": "Tricep Rope Pushdowns",
    "group": "arms",
    "art": "pushdown",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "1900.png",
    "muscles": [
     "Triceps"
    ],
    "wger": 1900
   },
   {
    "id": "w-clean-and-press",
    "name": "Clean and Press",
    "group": "shoulders",
    "art": "shoulderPressMachine",
    "equip": "barbell",
    "metric": "weight",
    "step": 2.5,
    "photo": "1901.jpg",
    "muscles": [
     "Shoulders"
    ],
    "wger": 1901
   },
   {
    "id": "w-weighted-push-ups",
    "name": "Weighted push-ups",
    "group": "chest",
    "art": "plank",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "1902.jpg",
    "muscles": [
     "Chest"
    ],
    "wger": 1902
   },
   {
    "id": "w-seated-cable-chest-fly",
    "name": "Seated Cable chest fly",
    "group": "chest",
    "art": "cableCrossover",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "1922.jpg",
    "muscles": [
     "Chest"
    ],
    "wger": 1922
   },
   {
    "id": "w-dumbbell-snatch",
    "name": "dumbbell snatch",
    "group": "legs",
    "art": "kettlebell",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1947.jpg",
    "muscles": [
     "Hamstrings",
     "Glutes",
     "Quads"
    ],
    "wger": 1947
   },
   {
    "id": "w-step-jack",
    "name": "Step Jack",
    "group": "cardio",
    "art": "treadmill",
    "equip": "bodyweight",
    "metric": "cardio",
    "step": 2.5,
    "photo": "1962.png",
    "muscles": [
     "Quads"
    ],
    "wger": 1962
   },
   {
    "id": "w-slow-squat",
    "name": "Slow Squat",
    "group": "legs",
    "art": "plank",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 5,
    "photo": "1963.png",
    "muscles": [
     "Quads"
    ],
    "wger": 1963
   },
   {
    "id": "w-marching-high-knees",
    "name": "Marching High Knees",
    "group": "legs",
    "art": "pullupBar",
    "equip": "bodyweight",
    "metric": "reps",
    "step": 2.5,
    "photo": "1965.png",
    "muscles": [
     "Quads"
    ],
    "wger": 1965
   },
   {
    "id": "w-single-arm-dumbbell-shoulder-press",
    "name": "Single-arm dumbbell shoulder press",
    "group": "shoulders",
    "art": "shoulderPressMachine",
    "equip": "dumbbell",
    "metric": "weight",
    "step": 2,
    "photo": "1968.png",
    "muscles": [
     "Shoulders"
    ],
    "wger": 1968
   },
   {
    "id": "w-mentzer-pulldown",
    "name": "Mentzer Pulldown",
    "group": "arms",
    "art": "latPulldown",
    "equip": "cable",
    "metric": "weight",
    "step": 2.5,
    "photo": "1971.jpg",
    "muscles": [
     "Biceps"
    ],
    "wger": 1971
   }
  ];

  if (!global.Machines) { console.error('wger.js loaded before machines.js'); return; }

  Object.keys(PHOTOS).forEach(function (id) {
    var ex = global.Machines.EXERCISES.filter(function (e) { return e.id === id; })[0];
    if (ex) ex.photo = DIR + PHOTOS[id];
  });

  EXTRA.forEach(function (e) {
    e.photo = DIR + e.photo;
    e.unilateral = false;
    global.Machines.EXERCISES.push(e);
  });

  global.Machines.PHOTO_DIR = DIR;
  global.Machines.WGER_COUNT = EXTRA.length + Object.keys(PHOTOS).length;
})(window);
